---
- name: Install Redis Server
  apt: name=redis-server state=latest
  become_user: root

- name: Ensure Redis Server is running
  service: name=redis-server state=started enabled=yes
  become_user: root
