---
- name: Install Rails
  hosts: webserver
  remote_user: deployer
  gather_facts: true
  pre_tasks:
    - name: installing ansible dependencies
      raw: sudo apt-get -y install python3 python3-simplejson python3-apt python python-simplejson python-apt

  vars:
    sidekiq_token: 0d61cad4:90c8679e
    datadog_api_key: 002bab24d4d6a38d25b531a8a7b17f62
    datadog_config:
      tags: "new_environment"
      log_level: INFO
      apm_enabled: "true" # has to be set as a string
      logs_enabled: true  # log collection is available on agent 6
    datadog_config_ex:
      trace.config:
        env: new_environment
      trace.concentrator:
        extra_aggregators: version
    datadog_checks:
      nginx:
        init_config:
        instances:
          - nginx_status_url: http://localhost/nginx_status/
      mcache:
        init_config:
        instances:
          - url: localhost
      redisdb:
        init_config:
        instances:
          - host: localhost
            port: 6379
          - host: guaruja-solvian.redis.cache.windows.net
            port: 6379
            password: tLi5sx55Q9M5Z1GyqgT2Y+6yuEFg3C9Snqw5P9DD6fs=
      postgres:
        init_config:
        instances:
          - host: hml-timescale.postgres.database.azure.com port
            port: 5432
            username: solvian@hml-timescale
            password: sQdDNuPx5ab8
            tags:
              - hosted
      mysql:
        init_config:
        instances:
          - host: hml-timescale.postgres.database.azure.com port
            port: 5432
            username: solvian@hml-timescale
            password: sQdDNuPx5ab8
            tags:
              - hosted

  roles:
    - common
    - {
        role: rvm_io.ruby,
        tags: ruby,
        rvm1_rubies: ['ruby-2.3'],
        rvm1_install_flags: '--auto-dotfiles --user-install',
        rvm1_user: deployer
      }
    - wkhtmltox
    - ruby_config
    - nginx_passenger
    - redis
    - memcached
    - { role: Datadog.datadog, become: yes }


