---
- name: Install Rails
  hosts: webserver
  gather_facts: true
  become: yes
  become_user: deployer
  vars_files:
    - vars/production.yml

  roles:
    - common
    - role: zzet.rbenv
      rbenv_users:
        - deployer
    - wkhtmltox
    - ruby_config
    - nginx_passenger
    - redis
    - memcached
    - { role: Datadog.datadog, become_user: root }


