---
- name: Install Rails
  hosts: webserver
  gather_facts: true
  become: yes
  become_user: deployer
  include_vars: vars/production.yml

  roles:
    - common
    - {
        role: rvm.ruby,
        tags: ruby,
        rvm1_rubies: ['ruby-2.5'],
        rvm1_install_flags: '--auto-dotfiles --user-install',
        rvm1_user: deployer
      }
    - wkhtmltox
    - ruby_config
    - nginx_passenger
    - redis
    - memcached
    - { role: Datadog.datadog, become_user: root }


