---
- name: Install Rails,
  hosts: all
  remote_user: deployer
  become: true
  gather_facts: true
  pre_tasks:
    # - name: fix update
    #   raw: sudo date -s "$(curl -s --head http://google.com | grep ^Date: | sed 's/Date: //g') -0500"
    - name: installing ansible dependencies
      raw: sudo apt-get -y install python3 python3-simplejson python3-apt python python-simplejson python-apt

  roles:
    - common
    - {
        role: rvm_io.ruby,
        tags: ruby,
        rvm1_rubies: ['ruby-2.3'],
        rvm1_install_flags: '--auto-dotfiles --user-install',
        rvm1_user: deployer
      }
    - nginx_passenger
