---
- name: set gemrc
  raw: 'echo "gem: --no-document" > ~/.gemrc'
  become_user: deployer

- name: parallel bundle
  shell: source /home/deployer/.profile &&  bundle config --global jobs 8
  become_user: deployer
  args:
    executable: /bin/bash
